version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /app/docker_credentials/username
    DOCKER_REGISTRY_PASSWORD: /app/docker_credentials/password
    DOCKER_REGISTRY_URL: /app/docker_credentials/url
phases:
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/todo-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/todo-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
